#Get all book
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###
#Add a book
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "Harry potter" 
}

###
#Update a book
PUT http://localhost:3001/books/80ff HTTP/1.1
Content-Type: application/json

{
    "title": "dark tower"
}

###
#Delete a book
DELETE http://localhost:3001/books/43ab HTTP/1.1
Content-Type: application/json